  import java.util.*;
  public class ConvertHash{
    public static void main(String[] args) {
        List<String> names= Arrays.asList("java", "python", "c++");
        ArrayList<String> list = new ArrayList<String>();
        list.addAll(names);
        System.out.println(list);
        List<Integer> hashList=list.stream().map(lang->lang.hashCode()).toList();
        System.out.println(hashList);
    }
}

///////////////////////////////////////////////////////////////////////////////////////////////////////////
///
////What is hash code?
////Hash code is a unique identifier for an object.
/// It is used to store and retrieve objects in a hash-based data structure,
/// such as a HashMap or HashSet. The hash code is generated by the object's 
///hashCode() method, which returns an integer value that represents the object's 
///memory address or some other unique identifier. The hash code is used to determine the 
///bucket in which the object will be stored in the hash-based data structure, 
///and it is also used to compare objects for equality.
////////////////////////////////////////////////////////////////////////////////////////////////////////////
///scooping 
///local variable, instance variable, static variable
///local variable is defined inside a method and can only be accessed within that method.
///man in middle attack 
///